version: '3.7'

services:
  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=senha_forte_erp_ctdol_2024
    volumes:
      - db-data:/var/lib/mysql
      - ./mariadb-config.cnf:/etc/mysql/conf.d/frappe.cnf

  redis-cache:
    image: redis:6.2-alpine

  redis-queue:
    image: redis:6.2-alpine

  backend:
    image: frappe/erpnext:v14.15.0
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - GUNICORN_TIMEOUT=600
    volumes:
      - sites-data:/home/frappe/frappe-bench/sites
      - apps-data:/home/frappe/frappe-bench/apps

  frontend:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8084:80"
    depends_on:
      - backend
    volumes:
      - sites-data:/home/frappe/frappe-bench/sites
      - apps-data:/home/frappe/frappe-bench/apps

volumes:
  db-data:
  sites-data:
  apps-data:
