server {
    listen 80 default_server;
    server_name _;
    resolver 127.0.0.11 valid=30s;

    proxy_read_timeout 600s;
    proxy_connect_timeout 600s;
    proxy_send_timeout 600s;

    location /assets/ {
        alias /home/frappe/frappe-bench/sites/assets/;
        try_files $uri =404;
    }

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host erp.ctdol.com.br;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
